### PR TITLE
Added the base setup

### PR DESCRIPTION
**Pull request by stienis96**
Probably needs some more work before merging. @geoffreyvd do you think we can make this work with your config files or did you already have something else in mind?

### CODE REVIEW

**Review by geoffreyvd — APPROVED** [review]
Yep much better and simpler starting point

**Comment by geoffreyvd** [comment]
config files can easily be merged without conflict. You could also consider deleting the greeting sample files.

**Review by l8518 — APPROVED** [review]
looks great :fire:

**Review by luusluus — APPROVED** [review]
top

**Pull request merged**
