### PR TITLE
Check predecessor

### PR DESCRIPTION
**Pull request by luusluus**
Put all asks in try catch.

Added check predecessor.
TODO: need also check successor
TODO: need to set new pred and or succ when node leaves at SIGINT leave.

### CODE REVIEW

**Comment by l8518** [comment]
@luusluus Do you mind merging latest develop, and then I could test it quite easily in a dockerized setup :-)

**Comment by luusluus** [comment]
Hey @l8518 not finished yet with this implementation, or it doesn't matter?

**Comment by stienis96** [comment]
@luusluus Still has merge conflicts. And doesn't work yet as described in chapter 5.2 of the 2003 paper.

**Comment by stienis96** [comment]
Works on my machine.

**Pull request merged**
